server:
  port: @gateway_server_port@
spring:
  application:
    name: crm-gateway
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
        - id: crm-customer         #规则名称 客户管理
          uri: lb://crm-customer   #目标服务地址
          predicates:
            - Path=/api/customer/**
          filters:
            - StripPrefix=2
        - id: crm-system    #系统管理
          uri: lb://crm-system
          predicates:
            - Path=/api/system/**
          filters:
            - StripPrefix=2
        - id: crm-marketing   #营销管理
          uri: lb://crm-marketing
          predicates:
            - Path=/api/marketing/**
          filters:
            - StripPrefix=2
        - id: crm-report    #统计管理
          uri: lb://crm-report
          predicates:
            - Path=/api/report/**
          filters:
            - StripPrefix=2
        - id: crm-service   #服务管理
          uri: lb://crm-service
          predicates:
            - Path=/api/service/**
          filters:
            - StripPrefix=2
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
            allowedHeaders: "*"
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://@eureka_server_host@:@eureka_server_port@/eureka/
swagger:
  global-operation-parameters:
tokenfilter:
  whiteList: .*login|.*api-docs  #自定义不进行认证拦截路径白名单